[package]
name = "cartridge-debug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.11.1"
cartridge = { path = "../cartridge" }
tileset = { path = "../tileset" }